# Configuration for Community Solar Accelerator Simulation

# Place this file in the same directory as app.py

distributions:
  # Simulation parameters
  # - label: "Simulation Years"
  #   min_value: 1
  #   p10: 5
  #   p50: 10
  #   p90: 15
  #   max_value: 25
  #   use_fixed: true
  #   fixed_value: 25

  # - label: "Private Equity Return Year"
  #   min_value: 1
  #   p10: 5
  #   p50: 10
  #   p90: 15
  #   max_value: 25
  #   use_fixed: true
  #   fixed_value: 10

  # Equity and seed inputs

  - label: "Retail Price (CAD/kWh)"
    min_value: 0.0
    p10: 0.07
    p50: 0.10
    p90: 0.13
    max_value: 0.25
    use_fixed: true
    fixed_value: 0.10
    step: 0.01


  - label: "PPA Price (CAD/kWh)"
    min_value: 0.0
    p10: 0.05
    p50: 0.07
    p90: 0.09
    max_value: 0.20
    use_fixed: true
    fixed_value: 0.05
    step: 0.01

  - label: "Debt Financing (%)"
    min_value: 10.0
    p10: 20.0
    p50: 40.0
    p90: 60.0
    max_value: 100.00
    use_fixed: true
    fixed_value: 50.0
    step: 1.0

  - label: "Opex per Project (CAD/project)"
    min_value: 0
    p10: 1000
    p50: 1500
    p90: 2000
    max_value: 20000
    use_fixed: false
    fixed_value: 2000
    step: 100

  - label: "Public Seed Grant (CAD)"
    min_value: 100000
    p10: 1000000
    p50: 2000000
    p90: 4000000
    max_value: 50000000
    use_fixed: true
    fixed_value: 1000000
    step: 100000

  - label: "Private Investment (CAD)"
    min_value: 100000
    p10: 1000000
    p50: 2000000
    p90: 4000000
    max_value: 50000000
    use_fixed: true
    fixed_value: 1000000
    step: 100000

  - label: "Projects per Year"
    min_value: 5
    p10: 6
    p50: 10
    p90: 14
    max_value: 20
    use_fixed: false
    fixed_value: 10
    step: 1

  - label: "Project Size (kW)"
    min_value: 10
    p10: 50
    p50: 100
    p90: 250
    max_value: 1000
    use_fixed: false
    fixed_value: 100
    step: 1

  - label: "Installed Cost (CAD/W)"
    min_value: 0.01
    p10: 0.8
    p50: 1.0
    p90: 1.40
    max_value: 2.0
    use_fixed: false
    fixed_value: 1.0
    step: 0.01

  - label: "Capacity Factor (%)"
    min_value: 0.0
    p10: 17.0
    p50: 20.0
    p90: 22.0
    max_value: 25.0
    use_fixed: false
    fixed_value: 20.0
    step: 0.01

  - label: "Debt Interest Rate (%)"
    min_value: 0.0
    p10: 3.0
    p50: 4.0
    p90: 6.0
    max_value: 10.0
    use_fixed: false
    fixed_value: 4.0
    step: 0.01

  - label: "Target Investor Return (%)"
    min_value: 0.0
    p10: 6.0
    p50: 7.0
    p90: 10.0
    max_value: 12.0
    use_fixed: true
    fixed_value: 4.0
    step: 0.01

  - label: "Corporate Tax Rate (%)"
    min_value: 0.0
    p10: 22.0
    p50: 25.0
    p90: 28.0
    max_value: 30.0
    use_fixed: true
    fixed_value: 25.0
    step: 0.01

  - label: "Cash Interest Rate (%)"
    min_value: 0.0
    p10: 0.0
    p50: 1.0
    p90: 2.0
    max_value: 5.0
    use_fixed: true
    fixed_value: 5.0
    step: 0.01

