system_output:
  label: "System Output (kWh)"
  min_value: 20_000
  p10: 30_000
  p50: 75_000
  p90: 200_000
  max_value: 1_000_000
  use_fixed: false
  fixed_value: 75_000
  step: 1000
  years: 1
  description: "The system output during year 0"
  units: "kWh"
  scenario: Base

panel_power:
  label: "Panel Power (W)"
  min_value: 300
  p10: 350
  p50: 400
  p90: 450
  max_value: 550
  use_fixed: false
  fixed_value: 400
  step: 25
  years: 1
  description: "The power rating of each solar panel in watts. This affects the total energy output of the solar installation."
  units: "W"
  scenario: Base

capacity_factor:
  label: "Capacity Factor (%)"
  min_value: 0.0
  p10: 16.0
  p50: 18.0
  p90: 21.0
  max_value: 25.0
  use_fixed: false
  fixed_value: 20.0
  step: 0.1
  description: "The percentage of time the solar panels are producing energy at their maximum capacity. This is influenced by location, weather, and panel orientation."
  units: "%"
  years: 1
  scenario: Base

number_of_panels:
  label: "Number of Panels (#)"
  min_value: 10
  p10: 100
  p50: 300
  p90: 2000
  max_value: 12500
  use_fixed: false
  fixed_value: 600
  step: 10
  years: 1
  description: "The total number of solar panels in the installation. This directly affects the total energy output and cost of the project."
  units: "#"
  scenario: Base

degradation_rate:
  label: "Degradation Rate (%)"
  min_value: 0.0
  p10: 0.3
  p50: 0.5
  p90: 0.7
  max_value: 1.0
  use_fixed: false
  fixed_value: 0.5
  step: 0.1
  years: 1
  description: "The annual decrease in the efficiency of solar panels. A lower degradation rate means the panels will produce energy more efficiently over time."
  units: "%"
  scenario: Base

install_cost:
  label: "Install Cost ($CAD/W)"
  min_value: 0.01
  p10: 2.5
  p50: 3
  p90: 3.5
  max_value: 5
  use_fixed: false
  fixed_value: 1.0
  step: 0.1
  years: 1
  description: "The cost of installing the solar panels per watt. This includes labor, materials, and other associated costs."
  units: "$CAD/W"
  scenario: Base

electricity_price:
  label: "Electricity Price ($CAD/kWh)"
  min_value: 0.01
  p10: 0.06
  p50: 0.14
  p90: 0.22
  max_value: 0.40
  use_fixed: false
  fixed_value: 0.30
  step: 0.01
  description: "The price of electricity per kilowatt-hour. This affects the revenue generated from selling excess energy back to the grid."
  units: "$CAD/kWh"
  scenario: Base

debt_interest_rate:
  label: "Debt Interest Rate (%)"
  min_value: 0.0
  p10: 3.0
  p50: 4.0
  p90: 6.0
  max_value: 10.0
  use_fixed: false
  fixed_value: 4.0
  step: 0.01
  years: 1
  description: "The interest rate on any loans taken to finance the solar project. A lower rate reduces the cost of borrowing and increases profitability."
  units: "%"
  scenario: Base

dividend_rate:
  label: "Dividend Rate (%)"
  min_value: 0.0
  p10: 2.0
  p50: 4.0
  p90: 6.0
  max_value: 12.0
  use_fixed: false
  fixed_value: 4.0
  step: 0.1
  years: 1
  description: "The specified return on investment for the capital used in the solar project. This is a key factor in determining the financial viability of the project."
  units: "%"
  scenario: Base

capital_return_year:
  label: "Capital Return Year (#)"
  min_value: 0.0
  p10: 4.0
  p50: 10.0
  p90: 15.0
  max_value: 25.0
  use_fixed: false
  fixed_value: 4.0
  step: 0.1
  years: 1
  description: "The year in which the capital return is expected to be achieved. This is important for financial planning and cash flow management."
  units: "#"
  scenario: Base

dividend_start_year:
  label: "Dividend Start Year (#)"
  min_value: 0.0
  p10: 1.0
  p50: 3.0
  p90: 5.0
  max_value: 25.0
  use_fixed: true
  fixed_value: 3.0
  step: 0.1
  years: 1
  description: "The year when dividends are expected to start being paid out to investors. This is crucial for attracting investment and ensuring financial sustainability."
  units: "#"
  scenario: Base

return_period:
  label: "Dividend Return Period (#)"
  min_value: 0.0
  p10: 5.0
  p50: 10.0
  p90: 15.0
  max_value: 25.0
  use_fixed: false
  fixed_value: 5.0
  step: 1.0
  years: 1
  description: "The number of years over which capital is returned"
  units: "#"
  scenario: Base

inflation_rate:
  label: "Inflation Rate (%)"
  min_value: 0.0
  p10: 1.0
  p50: 2.0
  p90: 3.0
  max_value: 5.0
  use_fixed: false
  fixed_value: 2.0
  step: 0.01
  years: 1
  description: "The expected rate of inflation over the project's lifetime. This affects the real value of costs and revenues, impacting overall profitability."
  units: "%"
  scenario: Base

admin_rate:
  label: "Administration Rate (%)"
  min_value: 0.0
  p10: 0.3
  p50: 0.5
  p90: 0.7
  max_value: 1.5
  use_fixed: false
  fixed_value: 0.5
  step: 0.01
  years: 1
  description: "The amount of administrative costs for the project as a function of capital expenditure. This includes management, legal, and other overhead costs."
  units: "%"
  scenario: Base

maintenance_rate:
  label: "Maintenance Rate (%)"
  min_value: 0.0
  p10: 0.3
  p50: 0.5
  p90: 0.7
  max_value: 1.5
  use_fixed: false
  fixed_value: 0.5
  step: 0.01
  years: 1
  description: "The annual maintenance costs as a percentage of the total capital expenditure. This includes repairs, cleaning, and other ongoing maintenance activities."
  units: "%"
  scenario: Base

discount_rate:
  label: "Discount Rate (%)"
  min_value: 0.0
  p10: 3.0
  p50: 4.0
  p90: 6.0
  max_value: 10.0
  use_fixed: false
  fixed_value: 4.0
  step: 0.01
  years: 1
  description: "The discount rate used for calculating the present value of future cash flows. This is important for assessing the financial viability of the project over time."
  units: "%"
  scenario: Base

insurance_rate:
  label: "Insurance Rate (%)"
  min_value: 0.0
  p10: 0.3
  p50: 0.5
  p90: 0.7
  max_value: 1.5
  use_fixed: false
  fixed_value: 0.2
  step: 0.01
  years: 1
  description: "The cost of insurance for the solar project as a percentage of the total capital expenditure. This covers risks such as damage, theft, and liability."
  units: "%"
  scenario: Base

public_funding_percent:
  label: "Public Funding Percentage (%)"
  min_value: 0.0
  p10: 25.0
  p50: 50.0
  p90: 75.0
  max_value: 100.0
  use_fixed: false
  fixed_value: 50.0
  step: 1.0
  years: 1
  description: "The percentage of the total project cost that is covered by public funding or investment. This can significantly affect the financial viability of the project."
  units: "%"
  scenario: Base

funding_buffer_percent:
  label: "Funding Buffer Percentage (%)"
  min_value: 0.0
  p10: 5.0
  p50: 10.0
  p90: 15.0
  max_value: 20.0
  use_fixed: false
  fixed_value: 10.0
  step: 1.0
  years: 1
  description: "The percentage of the total project cost set aside as a buffer for unexpected expenses or cost overruns. This helps ensure the project remains financially viable."
  units: "%"
  scenario: Base

itc_rate:
  label: "Investment Tax Credit Rate (%)"
  min_value: 0.0
  p10: 5.0
  p50: 10.0
  p90: 15.0
  max_value: 30.0
  use_fixed: true
  fixed_value: 30.0
  step: 1.0
  years: 1
  description: "The percentage of the total project cost that can be claimed as an investment tax credit, reducing the overall tax burden and improving cash flow."
  units: "%"
  scenario: Base

itc_year:
  label: "Investment Tax Credit Year (#)"
  min_value: 0
  p10: 1
  p50: 2
  p90: 3
  max_value: 25
  use_fixed: true
  fixed_value: 2
  step: 1
  years: 1
  description: "The year in which the investment tax credit is expected to be claimed. This is important for cash flow planning and tax strategy."
  scenario: Base

start_year_proportion:
  description: The percentage of year 0 that the project is active
  fixed_value: 0.25
  label: Year 0 Proportion (%)
  max_value: 0.0
  min_value: 1.0
  p10: 0.25
  p50: 0.5
  p90: 0.75
  step: 0.01
  units: "%"
  use_fixed: false
  years: 1
  scenario: Base
